name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage. Use flutter_secure_storage for the full flutter package.
repository: https://github.com/mogol/flutter_secure_storage
version: 2.0.0-beta.2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_secure_storage_platform_interface: ^1.1.1
  web: ">=1.0.0 <2.0.0"
  js: ^0.7.1

dev_dependencies:
  lint: ^2.0.0
dart:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
