name: flutter_secure_storage_windows
description: Windows implementation of flutter_secure_storage. Please use flutter_secure_storage instead of this package.
repository: https://github.com/mogol/flutter_secure_storage
version: 3.1.6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0
  plugin_platform_interface: ^2.1.8
  win32: ^5.9.0

dev_dependencies:
  lint: ^2.3.0

dart:
  plugin:
    implements: flutter_secure_storage
    platforms:
      windows:
        pluginClass: FlutterSecureStorageWindowsPlugin
        dartPluginClass: FlutterSecureStorageWindows
