name: flutter_secure_storage_windows
description: Windows implementation of flutter_secure_storage. Please use flutter_secure_storage instead of this package.
repository: https://github.com/mogol/flutter_secure_storage
version: 3.1.5

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  ffi: ^2.0.0
  path: ^1.8.0
  plugin_platform_interface: ^2.1.8
  win32: ^5.0.0

dev_dependencies:
  lint: ^2.0.0

dart:
  plugin:
    implements: flutter_secure_storage
    platforms:
      windows:
        pluginClass: FlutterSecureStorageWindowsPlugin
        dartPluginClass: FlutterSecureStorageWindows
